import ProductsList from '@/components/product/product-list';
import Trending from '@/components/trending/trending';
import Head from 'next/head';
import { getAllProducts } from './api';

const HomePage = ({ trendProducts, recommendProducts }) => {
	return (
		<>
			<Head>
				<title>Entertainment Web App Next.js | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Trending products={trendProducts} />
			<ProductsList products={recommendProducts} title="Recommended for you" />
		</>
	);
};

export const getStaticProps = async () => {
	const products = await getAllProducts();
	const trendProducts = products.filter((product) => product.isTrending);
	const recommendProducts = products.filter((product) => !product.isTrending);
	return {
		props: { trendProducts, recommendProducts },
	};
};

export default HomePage;
